@startuml Diagrama de Clases 
class Equipo{
 +Nombre : string
 -Registros : string
}

class Jugador{
 +Numero : int
 +Posicion : string
 +Teléfono : int
 +Nombre : string
 +Dirección : string
}

class Capitan{

}

class Entrenador{
 +Nivel_de_acreditación : string
 +Años_de_experiencia : int
 +Teléfono : int
 +Nombre : string
 +Dirección : string
}


class Juego{
 +Localidad : string
 +Puntuación : int
}

Equipo "1" *-- "6..20" Jugador
Jugador <|-- Capitan
Equipo "1" -- "1" Capitan : tiene
Equipo "1" --> "0..1" Entrenador : puede tener
Equipo "many" <-- "1" Entrenador : puede entrenar
Equipo "many" --> "many" Juego : compiten
@enduml

@startuml Diagrama de Objetos

object Equipo1 {
    Nombre = "Tigres de Aragua"
    Registros = "Campeón 2023"
}

object Equipo2 {
    Nombre = "Leones del Caracas"
    Registros = "Subcampeón 2023"
}

object Equipo3{
    Nombre = "Navgantes Magallanes"
    Registros = "Tercer Lugar 2023"
}

object Jugador1 {
    Numero = 10
    Posición = "Libero"
    Teléfono = 04142867590
    Nombre = "Adalberto Vieira"
    Dirección = "Calle 123"
}

object Jugador2 {
    Numero = 7
    Posición = "Opuesto"
    Teléfono = 04242595820
    Nombre = "Javier Molina"
    Dirección = "Avenida 456"
}

object Jugador3 {
    Numero = 8
    Posición = "Armador"
    Teléfono = 04162645234
    Nombre = "Juan Pérez"
    Dirección = "UCV"
}

object Jugador4 {
    Numero = 45
    Posición = "Punta"
    Teléfono = 04129356766
    Nombre = "Luis Gómez"
    Dirección = "Montalban"
}

object Capitan1 {
    Numero = 30
    Posición = "Centro"
    Nombre = "Carlos Sánchez"
    Teléfono = 111222333
    Dirección = "Plaza Central"
}

object Capitan2 {
    Numero = 90
    Posición = "Opuesto"
    Nombre = "Jose Marin"
    Teléfono = 1234567989
    Dirección = "Calle Ecuador"
}

object Capitan3 {
    Numero = 64
    Posición = "Punta"
    Nombre = "Antonio Da Silva"
    Teléfono = 987654321
    Dirección = "Calle Bolivia"
}

object Entrenador1 {
    Nivel_de_acreditación = "Profesional"
    Años_de_experiencia = 10
    Teléfono = 555666777
    Nombre = "Ana Martínez"
    Dirección = "Calle Nueva 789"
}

object Juego1 {
    Localidad = "Estadio Nacional"
    Puntuación = 3
}

object Juego2 {
    Localidad = "Estadio Local"
    Puntuación = 1
}

Equipo1 *-- Jugador1
Equipo1 *-- Jugador2
Equipo2 *-- Jugador3
Equipo3 *-- Jugador4
Equipo1 -- Capitan1 : tiene
Equipo2 -- Capitan2 : tiene
Equipo3 -- Capitan3 : tiene
Equipo1 --> Entrenador1 : puede tener
Entrenador1 --> Equipo2 : puede entrenar
Equipo1 --> Juego1 : compite
Equipo2 --> Juego1 : compite
Equipo2 --> Juego2 : compite
Equipo3 --> Juego2 : compite

@enduml